### PR TITLE
Add download badge

### PR DESCRIPTION
**Pull request by psuryan**

### CODE REVIEW

**Review by pchakraborty1 — CHANGES_REQUESTED** [review]
The link should be: https://pepy.tech/project/dpm360-lightsaber

**Comment by psuryan** [comment]
Added download badge.

**Review by psuryan — COMMENTED** [review]
Sorry, accidentally closed your pull request @pchakraborty1. Can you please approve this?

**Comment by pchakraborty1** [comment]
Merging PR to bring in required changes. Change needs to done still on `main`

**Pull request merged**
